let stockProductos = [
  {
    id: 1,
    nombre: "zapatillas de moda",
    tipo: "Indumentaria",
    cantidad: 1,
    desc: "Las mejores zapatillas del mercado online",
    precio: 1200,
    talle: "L",
    img: "../img/borcegos.jpg",
  },
  {
    id: 2,
    nombre: "zapatillas de moda",
    tipo: "Indumentaria",
    cantidad: 1,
    desc: "Las mejores zapatillas del mercado online",
    precio: 1100,
    talle: "L",
    img: "../img/jordanp.webp",
  },
  {
    id: 3,
    nombre: "zapatillas de moda",
    tipo: "Indumentaria",
    cantidad: 1,
    desc: "Las mejores zapatillas del mercado online",
    precio: 1200,
    talle: "M",
    img: "../img/zapatillas_deportivas_mujer.jpg",
  },
  {
    id: 4,
    nombre: "zapatillas de moda",
    tipo: "Indumentaria",
    cantidad: 1,
    desc: "Las mejores zapatillas del mercado online",
    precio: 1400,
    talle: "M",
    img: "../img/zapatillas_trabajo.jpg",
  },
  {
    id: 5,
    nombre: "zapatillas de moda",
    tipo: "Indumentaria",
    cantidad: 1,
    desc: "Las mejores zapatillas del mercado online",
    precio: 1200,
    talle: "S",
    img: "../img/zapatillasdeportivas.png",
  },
  {
    id: 6,
    nombre: "zapatillas de moda",
    tipo: "Indumentaria",
    cantidad: 1,
    desc: "Las mejores zapatillas del mercado online",
    precio: 1200,
    talle: "S",
    img: "../img/zapatos.jpg",
  },
  {
    id: 7,
    nombre: "zapatillas de moda",
    tipo: "Indumentaria",
    cantidad: 1,
    desc: "Las mejores zapatillas del mercado online",
    precio: 1200,
    talle: "S",
    img: "../img/D_NQ_NP_693424-MLA49985058216_052022-W.jpg",
  },
  {
    id: 8,
    nombre: "zapatillas de moda",
    tipo: "Indumentaria",
    cantidad: 1,
    desc: "Las mejores zapatillas del mercado online",
    precio: 1200,
    talle: "S",
    img: "../img/zapatillas-new-balance-574-hombre-sport-ms574fsb_nb_02_i.jpg",
  },
];
